name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cypress run with env
        uses: cypress-io/github-action@v2
        with:
          env: password=${{ secrets.QAPASSWORD }},testEnv=qa
