name: Continuous Integration

on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          start: npm run -s test:run -- -e password=`${{ secrets.QAPASSWORD }}`,testEnv=qa
          parallel: false
          record: false
