name: Tests for Staging on Chrome, FF

on:
  workflow_dispatch:
    inputs:
      browser:
        description: Please type chrome or firerox
        default: chrome
        required: true
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 12 * * 2'

jobs:
  cypress-setup:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup before Integration Tests
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          record: true
          spec: cypress/integration/setup/setup.spec.js
        env:
          CYPRESS_password: ${{ secrets.STAGING_PASSWORD }}
          CYPRESS_testEnv: staging
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

cypress-tests:
    needs: cypress-setup
    if: always()
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.0-chrome91-ff89
      options: --user 1001
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run for Cypress Integration Tests
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          browser: ${{ github.event.inputs.browser }}
          record: true
          spec: cypress/integration/tests/**/*
          parallel: false
        env:
          CYPRESS_password: ${{ secrets.STAGING_PASSWORD }}
          CYPRESS_testEnv: staging
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
